#Local-PTAS-Backup

<#
.SYNOPSIS
Creating a 7 days of local CDAT backups in addition to shadowcopies and offsite backups


.DESCRIPTION
This script copies the backup generated by cdat and copies it into the appropriate day of the week folder
It checks the export.log (cdat backup log) to see if it ran today and if it ran successfully before copying any files

.PARAMETER LogLocation
Location of log file and its name
IE. F:\Data\Scripts\Powershell\LOGS\PTAS-Local-Backup.log
.PARAMETER DBFilePath
The current location of the database to be copied
IE. 'F:\Data\Server\CDATSW\database_backup'
.PARAMETER DBBackupLocation
The location of the new backup database
IE. 'F:\Backups\CDAT-LocalBackup'
.PARAMETER DBFileName
The part of the name of the database which will be used to find the correct file.
IE. 'PTAS.dmp'
.PARAMETER ExportLogName
The name of the CDAT backup file

#>

param(
        [Parameter(Mandatory=$true,HelpMessage='Location of Log file')][string]$LogLocation,
        [Parameter(Mandatory=$true,HelpMessage='DB FIle Path')][string]$DBFilePath,
        [Parameter(Mandatory=$true,HelpMessage='DB New Location Path')][string]$DBBackupLocation,
        [Parameter(Mandatory=$true,HelpMessage='DB FileName')][string]$DBFileName,
        [Parameter(Mandatory=$true,HelpMessage='DB FileName')][string]$ExportLogName

    )

    function Write-Log
{
    Param(
        [string]$logstring)

    $Time=Get-Date
    Add-Content $Logfile -value "$Time $logstring"
}

    $logFile = $LogLocation
    $logFileExists = Test-Path -path $logFile
    
    if ( $logFileExists -eq $True)
    {
        Remove-Item $logFile
        New-Item -ItemType File -Force -Path $logFile
    }
    else
    {
        New-Item -ItemType File -Force -Path $logFile
    }
    function ModDate
{
    Param(
        [string]$Date)
    if ($Date.length -eq 1) {
        $date = '0' + $Date
    }
 return $date
}
    Write-Log "Local PTAS Backup Begins"

#Check if CDAT backup ran today (Export.log)
$ExportLogFile = $DBFilePath +'\' + $ExportLogName
$ExportLogFileExists = Test-Path -path $ExportLogFile

If ($ExportLogFileExists -eq $True)
{
    $curDate = Get-Date -Uformat "%m/%d/%Y"
    $LastAccessed = (Get-item -Path $ExportLogFile).LastWriteTime
    $lastAccessed = (Moddate $lastAccessed.Month), (Moddate $lastAccessed.Day), (Moddate $lastAccessed.Year) -join "/"
    #Check to see CDAT backup ran
    IF ($curDate -eq $lastAccessed)
    {
        #check to see if the CDAT backup was successfull
        $BackupFinished = Select-String -Path $ExportLogFile -Pattern 'successfully completed' -Quiet
        If ($BackupFinished -eq $true)
        {   
            #Get the current day
            $curDay = (Get-Date).DayOfWeek

            $copyPath = $DBBackupLocation + "\" + $curDay
            $copyPathExist = Test-Path -path $copyPath
            $DBFile = $DBFilePath + "\" + $DBFileName

            If ($copyPathExist -eq $true)
                {
                Copy-Item $DBFile -Destination $copyPath
                }
            else
                {
                New-Item -ItemType "directory" -Path $copyPath
                Copy-Item $DBFile -Destination $copyPath
                }
            Write-Log "Local CDAT backup successful"    
        }
        else
        {
            Write-Log "CDAT Backup did finish correctly. Check the Export.log"
        }
    }
    else 
    {
        Write-Log "CDAT Backup did not run. Check date on Export.log"
    }
}
else 
    {
        Write-Log "No Export.log file exists"
    }
Write-Log "Local PTAS Backup Ends"